# Generated by Django 2.2.6 on 2019-11-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('In process', 'In process'), ('Ready', 'Ready')], default='R', max_length=10)),
                ('estimated', models.PositiveSmallIntegerField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('sprintNumber', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cumulative', models.PositiveIntegerField(blank=True, null=True)),
                ('productBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productBacklog.ProductBacklog')),
            ],
        ),
    ]
