# Generated by Django 2.2.6 on 2019-11-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbi',
            name='sprintNumber',
        ),
    ]
