# Generated by Django 2.2.6 on 2019-11-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0002_remove_pbi_sprintnumber'),
        ('sprintBacklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='sprintBacklog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprintBacklog.SprintBacklog'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('In process', 'In process'), ('Ready', 'Ready')], default='Ready', max_length=10),
        ),
    ]
