# Generated by Django 2.2.6 on 2019-10-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0002_pbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklog',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productBacklog.Project'),
        ),
    ]
