# Generated by Django 2.2.6 on 2019-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0003_auto_20191106_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='taskHours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
