# Generated by Django 2.2.6 on 2019-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0004_auto_20191025_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='sprintNumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
