# Generated by Django 2.2.6 on 2019-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0005_auto_20191025_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='cumulative',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
