# Generated by Django 2.2.6 on 2019-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0005_pbi_remainingtaskhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='taskHoursDone',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('In process', 'In process'), ('Unfinished', 'Unfinished'), ('Ready', 'Ready')], default='Ready', max_length=10),
        ),
    ]
