# Generated by Django 2.2.6 on 2019-11-06 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productBacklog', '0002_remove_pbi_sprintnumber'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('In process', 'In process')], default='In process', max_length=10)),
                ('estimated', models.PositiveSmallIntegerField()),
                ('effortsDone', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productBacklog.PBI')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintNumber', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('In process', 'In process')], default='In process', max_length=10)),
                ('ddl', models.DateTimeField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
