# Generated by Django 2.2.6 on 2019-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0002_auto_20191107_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintbacklog',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Finished', 'Finished'), ('In process', 'In process')], default='In process', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Finished', 'Finished'), ('In process', 'In process')], default='Ready', max_length=10),
        ),
    ]
