# Generated by Django 2.2.6 on 2019-11-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0003_auto_20191109_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintbacklog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
